HEADERS +=\
	$$PWD/runtime/base_loader_mgr.h \
	$$PWD/runtime/binary_reader.h \
	$$PWD/runtime/binary_writer.h \
	$$PWD/runtime/component_loader_mgr.h \
	$$PWD/runtime/helper.h \
	$$PWD/runtime/json_helper.h \
	$$PWD/runtime/layout_loader_mgr.h \
	$$PWD/runtime/math_tool.h \
	$$PWD/runtime/object_factory.h \
	$$PWD/runtime/object_loader.h \
	$$PWD/runtime/pip_config.h \
	$$PWD/runtime/rect.h \
	$$PWD/runtime/resource_holder.h \
	$$PWD/runtime/resource_mapping.h \
	$$PWD/runtime/singleton.h \
	$$PWD/runtime/sprite_tool.h \
	$$PWD/runtime/string_tool.h \
	$$PWD/runtime/extend/csb_animation.h \
	$$PWD/runtime/extend/layout_proxy.h \
	$$PWD/runtime/extend/tile_collision_node.h \
	$$PWD/runtime/extend/z_button.h \
	$$PWD/runtime/extend/z_textatlas.h \
	$$PWD/runtime/loaders/button_loader.h \
	$$PWD/runtime/loaders/camera_loader.h \
	$$PWD/runtime/loaders/checkbox_loader.h \
	$$PWD/runtime/loaders/component_loader.h \
	$$PWD/runtime/loaders/csb_animation_loader.h \
	$$PWD/runtime/loaders/image_loader.h \
	$$PWD/runtime/loaders/layout_component_loader.h \
	$$PWD/runtime/loaders/layout_loader.h \
	$$PWD/runtime/loaders/layout_proxy_loader.h \
	$$PWD/runtime/loaders/light_loader.h \
	$$PWD/runtime/loaders/listview_loader.h \
	$$PWD/runtime/loaders/loader_addin.h \
	$$PWD/runtime/loaders/loadingbar_loader.h \
	$$PWD/runtime/loaders/node_loader.h \
	$$PWD/runtime/loaders/pageview_loader.h \
	$$PWD/runtime/loaders/particle_loader.h \
	$$PWD/runtime/loaders/physicsbody_loader.h \
	$$PWD/runtime/loaders/richtext_loader.h \
	$$PWD/runtime/loaders/scrollview_loader.h \
	$$PWD/runtime/loaders/slider_loader.h \
	$$PWD/runtime/loaders/spot_light_loader.h \
	$$PWD/runtime/loaders/sprite3dloader.h \
	$$PWD/runtime/loaders/sprite_loader.h \
	$$PWD/runtime/loaders/textatlas_loader.h \
	$$PWD/runtime/loaders/textbmfont_loader.h \
	$$PWD/runtime/loaders/textfield_loader.h \
	$$PWD/runtime/loaders/text_loader.h \
	$$PWD/runtime/loaders/tile_collision_node_loader.h \
	$$PWD/runtime/loaders/widget_loader.h \
    $$PWD/runtime/layouts/base_layout_loader.h \
    $$PWD/runtime/layouts/layout_loader_v1.h \

SOURCES +=\
	$$PWD/runtime/base_loader_mgr.cpp \
	$$PWD/runtime/binary_reader.cpp \
	$$PWD/runtime/binary_writer.cpp \
	$$PWD/runtime/component_loader_mgr.cpp \
	$$PWD/runtime/helper.cpp \
	$$PWD/runtime/json_helper.cpp \
	$$PWD/runtime/layout_loader_mgr.cpp \
	$$PWD/runtime/math_tool.cpp \
	$$PWD/runtime/object_factory.cpp \
	$$PWD/runtime/object_loader.cpp \
	$$PWD/runtime/resource_holder.cpp \
	$$PWD/runtime/resource_mapping.cpp \
	$$PWD/runtime/sprite_tool.cpp \
	$$PWD/runtime/string_tool.cpp \
	$$PWD/runtime/extend/csb_animation.cpp \
	$$PWD/runtime/extend/layout_proxy.cpp \
	$$PWD/runtime/extend/tile_collision_node.cpp \
	$$PWD/runtime/extend/z_button.cpp \
	$$PWD/runtime/extend/z_textatlas.cpp \
	$$PWD/runtime/loaders/button_loader.cpp \
	$$PWD/runtime/loaders/camera_loader.cpp \
	$$PWD/runtime/loaders/checkbox_loader.cpp \
	$$PWD/runtime/loaders/component_loader.cpp \
	$$PWD/runtime/loaders/csb_animation_loader.cpp \
	$$PWD/runtime/loaders/image_loader.cpp \
	$$PWD/runtime/loaders/layout_component_loader.cpp \
	$$PWD/runtime/loaders/layout_loader.cpp \
	$$PWD/runtime/loaders/layout_proxy_loader.cpp \
	$$PWD/runtime/loaders/light_loader.cpp \
	$$PWD/runtime/loaders/listview_loader.cpp \
	$$PWD/runtime/loaders/loader_addin.cpp \
	$$PWD/runtime/loaders/loadingbar_loader.cpp \
	$$PWD/runtime/loaders/node_loader.cpp \
	$$PWD/runtime/loaders/pageview_loader.cpp \
	$$PWD/runtime/loaders/particle_loader.cpp \
	$$PWD/runtime/loaders/physicsbody_loader.cpp \
	$$PWD/runtime/loaders/richtext_loader.cpp \
	$$PWD/runtime/loaders/scrollview_loader.cpp \
	$$PWD/runtime/loaders/slider_loader.cpp \
	$$PWD/runtime/loaders/spot_light_loader.cpp \
	$$PWD/runtime/loaders/sprite3dloader.cpp \
	$$PWD/runtime/loaders/sprite_loader.cpp \
	$$PWD/runtime/loaders/textatlas_loader.cpp \
	$$PWD/runtime/loaders/textbmfont_loader.cpp \
	$$PWD/runtime/loaders/textfield_loader.cpp \
	$$PWD/runtime/loaders/text_loader.cpp \
	$$PWD/runtime/loaders/tile_collision_node_loader.cpp \
	$$PWD/runtime/loaders/widget_loader.cpp \
    $$PWD/runtime/layouts/base_layout_loader.cpp \
    $$PWD/runtime/layouts/layout_loader_v1.cpp \
